Jimmyhealer patch
ScafTeam/scaf-team pull request #33
Opened 2022-12-08 07:14 UTC by jimmyhealer

2022-12-08 07:23 UTC, jimmyhealer commented
新增 設計議題

API 請求方式

2022-12-09 17:14 UTC, jteng2127 requested changes
use lower camel case, ex:
- taskower -> taskOwner
- projectname ->projectName
- etc.

2022-12-09 17:14 UTC, jteng2127 commented on SDD/SDD.tex
> +	AMM-II-05    & /user/*uid     & Account Management Module & Client端            \\ \hline
```suggestion
	AMM-II-05    & /user/:uid     & Account Management Module & Client端            \\ \hline
```

2022-12-10 03:41 UTC, jimmyhealer commented on SDD/SDD.tex
> +	AMM-II-05    & /user/*uid     & Account Management Module & Client端            \\ \hline
為啥不用 "*" ?

2022-12-10 07:55 UTC, jteng2127 commented on SDD/SDD.tex
> +	AMM-II-05    & /user/*uid     & Account Management Module & Client端            \\ \hline
其他全都是用 `:uid` 跟 `:pn`
我不確定RESTful的寫法 不過gin之前聽你們說router寫法是用`/user/:uid`

2022-12-12 08:22 UTC, jteng2127 commented on SDD/SDD.tex
> +	AMM-II-05    & /user/*uid     & Account Management Module & Client端            \\ \hline
`*uid` 代表他可以被省略

2022-12-12 08:23 UTC, jteng2127 approved these changes

2022-12-12 08:24 UTC, merged